(() => {
  const D = window.VirtualInstagramData, S = window.VIStore, E = window.VIEditor, R = window.VIEditorRender;
  const $ = (s, r = document) => r.querySelector(s), $$ = (s, r = document) => Array.from(r.querySelectorAll(s));
  let feed = [], mine = [], currentPersonId = null, currentDetail = null, returnView = 'feed-view';
  const esc = (v) => String(v ?? '').replace(/[&<>'"]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const ago = (ts) => { const m=Math.max(1,Math.floor((Date.now()-Number(ts||Date.now()))/60000)); if(m<60)return `${m} 分鐘前`; const h=Math.floor(m/60); return h<24?`${h} 小時前`:`${Math.floor(h/24)} 天前`; };
  const follower = (n) => Number(n)>=10000?`${(Number(n)/10000).toFixed(1).replace('.0','')} 萬`:Number(n||0).toLocaleString('zh-TW');
  const postById = (id) => feed.find((p) => p.id === id) || null;
  const likeCount = (p) => Number(p.likes||0)+(S.isLiked(p.id)?1:0);

  function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1600);}
  function showView(id){$$('.view').forEach((v)=>v.classList.remove('active'));$('#'+id)?.classList.add('active');S.state().lastView=id;S.save();scrollTo({top:0,behavior:'instant'});}
  function openModal(id){$('#'+id)?.classList.add('open');} function closeModal(id){$('#'+id)?.classList.remove('open');}
  async function refresh(){mine=await S.getMyPosts();feed=await S.feedPosts();renderAll();}

  function renderStories(){const root=$('#stories');root.innerHTML='';D.people.forEach((p)=>{const b=document.createElement('button');b.className='story';b.innerHTML=`<img src="${p.avatar}" alt=""><span>${p.username}</span>`;b.onclick=()=>openProfile(p.id);root.appendChild(b);});}
  function media(post, onOpen){const box=document.createElement('div');box.className='carousel';const images=post.images?.length?post.images:[post.image];let i=0;const img=document.createElement('img');img.className='post-media';img.alt=`${post.username} 的貼文`;const dots=document.createElement('div');dots.className='carousel-dots';
    const sync=()=>{img.src=images[i];dots.innerHTML=images.map((_,j)=>`<span class="${j===i?'active':''}"></span>`).join('');};img.onclick=()=>onOpen?.();img.ondblclick=(e)=>{e.stopPropagation();S.toggleLike(post.id);renderFeed();if(currentDetail?.id===post.id)renderDetail(postById(post.id));};box.appendChild(img);
    if(images.length>1){const prev=document.createElement('button'),next=document.createElement('button');prev.className='carousel-arrow prev';next.className='carousel-arrow next';prev.textContent='‹';next.textContent='›';prev.onclick=(e)=>{e.stopPropagation();i=(i-1+images.length)%images.length;sync();};next.onclick=(e)=>{e.stopPropagation();i=(i+1)%images.length;sync();};box.append(prev,next,dots);}sync();return box;}
  function commentButton(id){const b=document.createElement('button');b.className='comment-icon';b.innerHTML='<span></span>';b.onclick=()=>openComments(id);return b;}
  function bookmarkButton(post){const b=document.createElement('button');b.className='bookmark'+(S.isSaved(post.id)?' saved':'');b.setAttribute('aria-label','收藏');b.innerHTML='<span></span>';b.onclick=()=>{S.toggleSaved(post.id);renderFeed();if(currentDetail?.id===post.id)renderDetail(postById(post.id));};return b;}

  function renderFeed(){const root=$('#feed');root.innerHTML='';feed.forEach((p)=>{const a=document.createElement('article');a.className='post';const head=document.createElement('div');head.className='post-head';head.innerHTML=`<img src="${p.avatar}" alt=""><div><button class="post-user">${esc(p.username)}</button>${p.location?`<small>${esc(p.location)}</small>`:''}</div>`;head.querySelector('img').onclick=()=>openOwner(p.ownerId);head.querySelector('.post-user').onclick=()=>openOwner(p.ownerId);
    const actions=document.createElement('div');actions.className='post-actions';const like=document.createElement('button');like.className=S.isLiked(p.id)?'liked':'';like.textContent=S.isLiked(p.id)?'♥':'♡';like.onclick=()=>{S.toggleLike(p.id);renderFeed();};const share=document.createElement('button');share.textContent='⌁';share.onclick=()=>sharePost(p);actions.append(like,commentButton(p.id),share,bookmarkButton(p));
    const meta=document.createElement('div');meta.innerHTML=`<div class="post-likes">${likeCount(p).toLocaleString('zh-TW')} 個讚</div><div class="post-caption"><strong>${esc(p.username)}</strong> ${esc(p.caption||'')}</div>${p.tags?.length?`<div class="post-tags">標註 ${p.tags.map(esc).join('、')}</div>`:''}<div class="post-time">${ago(p.createdAt)}</div>`;a.append(head,media(p,()=>openDetail(p.id,'feed-view')),actions,meta);root.appendChild(a);});}
  function openOwner(id){id==='me'?openMe():openProfile(id);}

  function openProfile(id){const p=S.personById(id);if(!p)return;currentPersonId=id;$('#profile-header-name').textContent=p.username;$('#profile-avatar').src=p.avatar;$('#profile-username').textContent=p.username;$('#profile-name').textContent=p.name;$('#profile-bio').textContent=p.bio;$('#profile-post-count').textContent=p.posts.length;$('#profile-followers').textContent=follower(p.followers+(S.isFollowing(id)?1:0));$('#profile-following').textContent=follower(p.following);syncFollow();const grid=$('#profile-grid');grid.innerHTML='';p.posts.forEach((raw)=>{const post=S.makeNpcPost(p,raw),b=document.createElement('button');b.innerHTML=`<img src="${post.images[0]}" alt="">`;b.onclick=()=>openDetail(post.id,'profile-view');grid.appendChild(b);});showView('profile-view');}
  function syncFollow(){const b=$('#follow-button'),on=S.isFollowing(currentPersonId);b.textContent=on?'追蹤中':'追蹤';b.classList.toggle('primary',!on);}
  function toggleFollow(){if(!currentPersonId)return;S.toggleFollow(currentPersonId);openProfile(currentPersonId);}

  function openMe(){renderMe();showView('me-view');}
  function renderMe(){const me=S.state().me;$('#me-header-name').textContent=me.username;$('#me-username').textContent=me.username;$('#me-name').textContent=me.name;$('#me-bio').textContent=me.bio;$('#me-avatar').src=me.avatar;$$('.me-avatar-small').forEach((i)=>i.src=me.avatar);$('#me-post-count').textContent=mine.length;const root=$('#me-grid');root.innerHTML='';mine.forEach((raw)=>{const p=S.makeMine(raw),b=document.createElement('button');b.innerHTML=`<img src="${p.images[0]}" alt="">`;b.onclick=()=>openDetail(p.id,'me-view');root.appendChild(b);});$('#empty-me').classList.toggle('hidden',mine.length>0);}

  function openDetail(id,from){const p=postById(id);if(!p)return;currentDetail=p;returnView=from||'feed-view';renderDetail(p);$('#detail-view').classList.add('active');}
  function renderDetail(p){currentDetail=p;$('#detail-subtitle').textContent=p.username;$('#detail-avatar').src=p.avatar;$('#detail-user').textContent=p.username;$('#detail-location').textContent=p.location||'';$('#detail-caption-user').textContent=p.username;$('#detail-caption').textContent=p.caption||'';$('#detail-tags').textContent=p.tags?.length?`標註 ${p.tags.join('、')}`:'';$('#detail-time').textContent=ago(p.createdAt);$('#detail-likes').textContent=`${likeCount(p).toLocaleString('zh-TW')} 個讚`;const heart=$('#detail-like');heart.textContent=S.isLiked(p.id)?'♥':'♡';heart.classList.toggle('liked',S.isLiked(p.id));const save=$('#detail-save');save.classList.toggle('saved',S.isSaved(p.id));save.innerHTML='<span></span>';$('#detail-options').style.visibility=p.isMine?'visible':'hidden';const m=$('#detail-media');m.innerHTML='';m.appendChild(media(p,null));}
  function closeDetail(){ $('#detail-view').classList.remove('active'); if(returnView==='me-view')openMe();else if(returnView==='profile-view'&&currentPersonId)openProfile(currentPersonId);else showView('feed-view'); }

  function openComments(id){currentDetail=postById(id);renderComments();openModal('comments-modal');setTimeout(()=>$('#comment-input').focus(),50);}
  function renderComments(){const root=$('#comments-list');root.innerHTML='';const list=S.comments(currentDetail?.id);if(!list.length){root.innerHTML='<div class="empty-comment">還沒有留言</div>';return;}list.forEach((c)=>{const row=document.createElement('div');row.className='comment-row';row.innerHTML=`<img src="${S.state().me.avatar}" alt=""><div><strong>${esc(c.author)}</strong><p>${esc(c.text)}</p><small>${ago(c.createdAt)}</small><div class="comment-tools"><button data-like>${c.liked?'♥':'♡'}</button>${c.mine?'<button data-delete>刪除</button>':''}</div></div>`;row.querySelector('[data-like]').onclick=()=>{S.toggleCommentLike(currentDetail.id,c.id);renderComments();};row.querySelector('[data-delete]')?.addEventListener('click',()=>{S.deleteComment(currentDetail.id,c.id);renderComments();});root.appendChild(row);});}

  async function sharePost(p){const text=`${p.username}：${p.caption||''}`;try{if(navigator.share)await navigator.share({title:'IG 模擬器貼文',text});else if(navigator.clipboard){await navigator.clipboard.writeText(text);toast('貼文內容已複製');}}catch{}}
  function openEditProfile(){const me=S.state().me;$('#profile-form-username').value=me.username;$('#profile-form-name').value=me.name;$('#profile-form-bio').value=me.bio;$('#profile-form-avatar').value='';openModal('profile-edit-modal');}
  async function saveProfile(e){e.preventDefault();const patch={username:$('#profile-form-username').value.trim()||S.state().me.username,name:$('#profile-form-name').value.trim()||S.state().me.name,bio:$('#profile-form-bio').value.trim()};const f=$('#profile-form-avatar').files?.[0];if(f)patch.avatar=await R.fileToDataURL(f,500,.82);S.updateMe(patch);closeModal('profile-edit-modal');await refresh();openMe();toast('個人資料已更新');}
  function openOptions(){if(currentDetail?.isMine)openModal('post-options-modal');}
  async function editCaption(){if(!currentDetail?.isMine)return;const next=prompt('編輯貼文文案',currentDetail.caption||'');if(next===null)return;const raw=mine.find((p)=>p.id===currentDetail.id);if(raw){raw.caption=next.trim();await S.putMyPost(raw);closeModal('post-options-modal');await refresh();currentDetail=postById(raw.id);renderDetail(currentDetail);}}
  async function deletePost(){if(!currentDetail?.isMine||!confirm('確定要刪除這篇貼文嗎？'))return;await S.deleteMyPost(currentDetail.id);closeModal('post-options-modal');$('#detail-view').classList.remove('active');currentDetail=null;await refresh();openMe();toast('貼文已刪除');}
  function editFullPost(){if(!currentDetail?.isMine)return;const raw=mine.find((p)=>p.id===currentDetail.id);closeModal('post-options-modal');$('#detail-view').classList.remove('active');if(raw)E.openExisting(raw);}

  function renderAll(){renderStories();renderFeed();renderMe();}
  function bind(){E.init();$$('.home-button').forEach((b)=>b.onclick=()=>showView('feed-view'));$$('.me-button').forEach((b)=>b.onclick=openMe);$$('.create-button').forEach((b)=>b.onclick=()=>openModal('create-sheet'));$('.back-button').onclick=()=>showView('feed-view');$$('.modal-close').forEach((b)=>b.onclick=()=>b.closest('.modal')?.classList.remove('open'));$$('.toast-button').forEach((b)=>b.onclick=()=>toast(b.dataset.toast||'功能預留'));
    $('#follow-button').onclick=toggleFollow;$('#detail-back').onclick=closeDetail;$('#detail-like').onclick=()=>{if(currentDetail){S.toggleLike(currentDetail.id);renderDetail(postById(currentDetail.id));renderFeed();}};$('#detail-comment').onclick=()=>currentDetail&&openComments(currentDetail.id);$('#detail-share').onclick=()=>currentDetail&&sharePost(currentDetail);$('#detail-repost').onclick=()=>toast('已模擬轉發');$('#detail-save').onclick=()=>{if(currentDetail){S.toggleSaved(currentDetail.id);renderDetail(postById(currentDetail.id));renderFeed();}};$('#detail-options').onclick=openOptions;
    $('#comment-form').onsubmit=(e)=>{e.preventDefault();S.addComment(currentDetail.id,$('#comment-input').value);$('#comment-input').value='';renderComments();};$('#create-post-choice').onclick=()=>{closeModal('create-sheet');E.openNew();};$('#edit-profile').onclick=openEditProfile;$('#avatar-add').onclick=openEditProfile;$('#share-profile').onclick=()=>{navigator.clipboard?.writeText(`@${S.state().me.username}｜${S.state().me.bio}`);toast('個人檔案資訊已複製');};$('#profile-form').onsubmit=saveProfile;$('#edit-caption-option').onclick=editCaption;$('#edit-post-option').onclick=editFullPost;$('#delete-post-option').onclick=deletePost;
    window.addEventListener('vi-editor-done',async()=>{await refresh();openMe();toast('貼文已更新');});window.addEventListener('vi-posts-change',refresh);}
  (async()=>{bind();await refresh();showView('feed-view');})();
})();
